logging:
  level:
    root: info
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            # 新版本 跨域解决
            allowedOriginPatterns: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: '*'
            allowCredentials: true
            exposedHeaders:
              - Access-Control-Expose-Headers
              - Authorization,X-Suggested-Filename,content-disposition,user_token
            maxAge: 360000
      x-forwarded:
        enabled: true
      routes:
        # 统一认证服务
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
        - id: file
          uri: lb://file
          predicates:
            - Path=/file/**
        - id: main
          uri: lb://main
          predicates:
            - Path=/main/**