logging:
  level:
    root: info
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 5
          max-wait: -1ms
          min-idle: 2
      database: 1